### ISSUE TITLE
upgrade winff with gtk3

### ISSUE THREAD

**Issue by torikulhabib** [WinFF/winff#237]
upgrade winff with gtk3

**Comment by paulgevers** [comment]
Can you please explain what you mean/want? The Widgetset is provided by Lazarus, so it means that you just need to recompile? Is that what you want? On which OS? For most (Linux) distributions, this is done by the distribution, and not by us.

Or did you try to recompile and did it fail? If so, could you provide the error you are seeing?

**Comment by paulgevers** [comment]
Seems like lazarus isn't ready yet: http://wiki.lazarus.freepascal.org/GTK3_Interface
