### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by ponypot** [WinFF/winff#242]
Hello

While doing some tests with winff, I noticed two issues that could lead to arbitrary command execution while processing files.

The fist one is due to the way filenames are inserted in the temporary shell scripts generated to convert the media. Due to the lack of character escaping, it is possible to insert system command using specially crafted filename such as 'aaa";xcalc;".avi' or "aaa$(xcalc).mp4' :

![1_quoteInName](https://user-images.githubusercontent.com/32674666/54448113-43601380-474b-11e9-97c3-0846236e2624.png)

![2_quoteInScript](https://user-images.githubusercontent.com/32674666/54448316-b7022080-474b-11e9-8949-21b53f216bf6.png)

![3_xcalc](https://user-images.githubusercontent.com/32674666/54448116-43f8aa00-474b-11e9-8702-fb0bb6d9dc90.png)

If a user tries to convert files from untrusted sources without checking their filename, it may lead to the compromising of his workstation.

The second issue is related to the permission of this script. As shown on the following picture, every users can access to them and modify them. Even if those files are only temporary and launched right after generation, it leads to a race-condition case where another user may try to replace the script content before its execution in order to execute its own command with the winff user permission.

![4_rwxrwxrwx](https://user-images.githubusercontent.com/32674666/54448118-44914080-474b-11e9-8f38-9317de0786d0.png)

Do you this it is possible to patch these issues?

Regard,

**Comment by PeterBBBBB** [comment]
Fix committed for arbitrary command execution [31b79e3]
Close #242

Not planning on doing script permissions.
Other users will not have write access to the .winff folder.
(Also Lazarus SaveToFile has no option to set permissions anyway)
