### ISSUE TITLE
compile winff?

### ISSUE THREAD

**Issue by mikysal78** [WinFF/winff#244]
on debian how-to compile winff?
no apt because ffmpeg and driver nvidia installed from source (no apt).
Thanks.

**Comment by paulgevers** [comment]
Hi Michele,

On 18-10-2019 01:49, Michele Salerno wrote:
> on debian how-to compile winff?
> no apt because ffmpeg and driver nvidia installed from source (no apt).

Why would $(apt install winff) not work for you? Winff doesn't care if
you built ffmpeg yourself or used apt to install it.

Anyways, the recipe is in the Debian source:
https://salsa.debian.org/pascal-team/winff/blob/master/debian/rules

It's basically:
lazbuild -B winff.lpr

Paul
