### ISSUE TITLE
ERR<13080>

### ISSUE THREAD

**Issue by Peacepill** [WinFF/winff#248]
When i am gonna to convert ERR<13080> shown in terminal,pls help

**Comment by paulgevers** [comment]
Hi @Peacepill 

Please copy/paste more context from the terminal into this bug report. "ERR<13080>" doesn't mean anything to me. Which terminal are you talking about, the one that pops-up by WinFF? Which OS or distribution are you running, Windows 10, Debian 10, SUSE ??.

**Comment by Peacepill** [comment]
> Hi @Peacepill
> 
> Please copy/paste more context from the terminal into this bug report. "ERR<13080>" doesn't mean anything to me. Which terminal are you talking about, the one that pops-up by WinFF? Which OS or distribution are you running, Windows 10, Debian 10, SUSE ??.

Hi, i am running Linux Bodhi 5.1,here is screenshot 
![shot-2020-03-06_14-51-31](https://user-images.githubusercontent.com/61851365/76077436-2060ec00-5fba-11ea-9695-a24f3b5bdd27.jpg)

**Comment by paulgevers** [comment]
When does this terminal appear? When you try to start Winff? In that case, contact the provider of you Winff package (Linux Bohdi) as there seems to be something wrong with the build.

**Comment by Peacepill** [comment]
> When does this terminal appear? When you try to start Winff? In that case, contact the provider of you Winff package (Linux Bohdi) as there seems to be something wrong with the build.

well i click on convert button

**Comment by paulgevers** [comment]
Under `Edit`, hit `Preferences`. In the pop-up window, select the `Linux` tab. Can you change the `Terminal to run FFmpeg in:` field to a different terminal than selected by x-terminal-emulator and see if the issue goes away? Seems like your terminal emulator doesn't work as expected. You can also play with the `Terminal Options`

**Comment by Peacepill** [comment]
> Under `Edit`, hit `Preferences`. In the pop-up window, select the `Linux` tab. Can you change the `Terminal to run FFmpeg in:` field to a different terminal than selected by x-terminal-emulator and see if the issue goes away? Seems like your terminal emulator doesn't work as expected. You can also play with the `Terminal Options`

Before used x-terminal-emulator and terminalogy,both didnot work.But xterm worked for me,thanks for attention.
