### ISSUE TITLE
Problem displaying pt_BR translation

### ISSUE THREAD

**Issue by marcelocripe** [WinFF/winff#252]
Hello dear WinFF developers.

The most recent translations of WinFF into Brazilian Portuguese are available at this URL:
https://github.com/marcelocripe/WinFF_pt_BR/blob/main/winff.pt_BR.po

I was able to perform tests on the "winff.pt_BR.po" file in WinFF 1.5.5-8, but the edits I made as root in the "winff.pt_BR.po" file in the "/usr/share/winff/languages" folder were not displayed in the graphical interface. It was only when I edited the "winff.pt.po" file that the graphical interface received my edits as root.
The tests I did were on the 64-bit antiX 21 operating system booted in LiveUSB mode in Brazilian Portuguese language. Please, I ask you to verify if the WinFF programming code is really capable of displaying the translations contained in the "winff.pt_BR.po" file.

Another volunteer translator also identified this issue with another language, as can be seen in this topic https://www.antixforum.com/forums/topic/antix-and-antix-application-program-translation-platforms/page/2/ #post-87727.

Thank you so much for creating and keeping WinFF alive.

marcelocripe
(Original text in Brazilian Portuguese language)

The attachment contains:

winff.pt_BR.po
winff.desktop
WinFF.pt_BR.odt

[WinFF.pt_BR_31-08-2022.zip](https://github.com/WinFF/winff/files/9479629/WinFF.pt_BR_31-08-2022.zip)

- - - - -

Olá caros desenvolvedores do WinFF.

As traduções mais recentes do WinFF o idioma Português do Brasil estão disponíveis neste URL:
https://github.com/marcelocripe/WinFF_pt_BR/blob/main/winff.pt_BR.po

Eu consegui realizar testes no arquivo "winff.pt_BR.po" no WinFF 1.5.5-8, mas as edições que eu fazia como root no arquivo "winff.pt_BR.po" da pasta "/usr/share/winff/languages" não eram exibidas na interface gráfica. Apenas quando eu editei o arquivo "winff.pt.po" que a interface gráfica recebia as minhas edições como root.
Os testes que eu fiz foram no sistema operacional antiX 21 de 64 bits inicializado no modo LiveUSB em idioma Português do Brasil. Por favor, eu peço que verifiquem se realmente o código de programação do WinFF é capaz de exibir as traduções contidas no arquivo "winff.pt_BR.po".

Um outro tradutor voluntário também identificou este problema com outro idioma, como pode ser conferido neste tópico https://www.antixforum.com/forums/topic/antix-and-antix-application-program-translation-platforms/page/2/#post-87727.

Muito obrigado por criar e manter o WinFF vivo.

marcelocripe
(Texto original em idioma Português do Brasil)

O anexo contém:

winff.pt_BR.po
winff.desktop
WinFF.pt_BR.odt

[WinFF.pt_BR_31-08-2022.zip](https://github.com/WinFF/winff/files/9479629/WinFF.pt_BR_31-08-2022.zip)

**Comment by PeterBBBBB** [comment]
Should be fixed in 1.6.
Please reopen if you still see problems here.

**Comment by marcelocripe** [comment]
> Should be fixed in 1.6.
> Please reopen if you still see problems here.

Thank you very much!

Muito obrigado!

**Comment by PeterBBBBB** [comment]
The issue here is that from the Documentation tab under the Help (Adjuda) menu,
WinFF only launches pdf files with a 2 character locale code.
So a WinFF.pt_BR.pdf will never be seen, and will default to WinFF.en.pdf.
As you say "it's better to have a translation than none." !!

I was alerted to this problem by the comment in the debian/rules file regarding the Spanish pdf
https://salsa.debian.org/pascal-team/winff/-/blob/master/debian/rules

It would of course be better if WinFF used 5 character locales for launching the pdfs, but until we have more than one dialect for any language, the point is moot.

Thanks for your translation. I'll include your desktop file in the next release. 
Let me know if you would like a name added to the Sobre -> Obrigardo box.

**Comment by marcelocripe** [comment]
> WinFF only launches pdf files with a 2 character locale code.
> So a WinFF.pt_BR.pdf will never be seen, and will default to WinFF.en.pdf.
> As you say "it's better to have a translation than none." !!

This same problem occurs with the translation file "winff.pt_BR.po", as I explained in the initial text of this topic.
This means that the Brazilian user needs to manually edit the names of the ".po" files to be able to have the "pt_BR" translation in the graphical interface. And both "pt" and "pt_BR" users will have access to the "pt_BR" translation of the help manual.

> It would of course be better if WinFF used 5 character locales for launching
> the pdfs, but until we have more than one dialect for any language, the point > is moot.

What we talked about here cannot be forgotten, because it would be very sad to lose the "pt_BR" translation if a native of Portugal made changes to the texts and images because they were unaware of our conversation.

> Thanks for your translation. I'll include your desktop file in the next release.

I'm grateful that you use the "winff.desktop" file that the antiX community works on to have translations for different languages. Menus also need to be translated. We maintain translations of several ".desktop" files that are gradually being accepted by program developers. Unfortunately, not all developers accept having the ".desktop" file translated.
The ".desktop" files that the antiX community works on to have translations of different languages are in these repositories:

https://gitlab.com/Robin-antiX/antix23-desktop-files/-/tree/main/applications?ref_type=heads
https://gitlab.com/antix-contribs/antix-desktop-files
https://app.transifex.com/anticapitalista/antix-development/antix23-desktop-files/

At some point we will have translations reviewed by native speakers of other languages that are not yet in the "winff.desktop" file and this will be very good for WinFF.

> Let me know if you would like a name added to the Sobre -> Obrigardo box.

Are you serious? You will include my name "marcelocripe" in the acknowledgments. That for me would be an honor.
I suggest adding the names of the other people who are involved in WinFF who have yet to be added.

Thank you very much!

- - - - -

> WinFF only launches pdf files with a 2 character locale code.
> So a WinFF.pt_BR.pdf will never be seen, and will default to WinFF.en.pdf.
> As you say "it's better to have a translation than none." !!

Este mesmo problema ocorre com o arquivo da tradução "winff.pt_BR.po", conforme eu expliquei no texto inicial deste tópico.
Isso significa que o usuário do Brasil precisa editar manualmente os nomes os arquivos ".po" para poderem ter na interface gráfica a tradução "pt_BR". E tanto os usuário "pt", quanto os usuário "pt_BR" terão acesso a tradução "pt_BR" do manual de ajuda.

> It would of course be better if WinFF used 5 character locales for launching
> the pdfs, but until we have more than one dialect for any language, the point > is moot.

Não pode ser esquecido o que conversamos aqui, porque seria muito triste perder a tradução "pt_BR" se um nativo de Portugal fizer as alterações nos textos e nas imagens por não saber da nossa conversa.

> Thanks for your translation. I'll include your desktop file in the next release.

Eu sou grato por você utilizar o arquivo "winff.desktop" que a comunidade antiX trabalha para ter as traduções de diversos idiomas. Os menus também precisam ser traduzidos. Nós mantemos as traduções de diversos arquivos ".desktop" que aos poucos estão sendo aceitos pelos desenvolvedores dos programas. Infelizmente, nem todos os desenvolvedores aceitam ter o arquivo ".desktop" traduzido.
Os arquivos ".desktop" que a comunidade antiX trabalha para ter as traduções de diversos idiomas estão nestes repositórios:
https://gitlab.com/Robin-antiX/antix23-desktop-files/-/tree/main/applications?ref_type=heads
https://gitlab.com/antix-contribs/antix-desktop-files
https://app.transifex.com/anticapitalista/antix-development/antix23-desktop-files/

Eu algum momento nós teremos as traduções revisadas por nativos de outros idiomas que ainda não estão no arquivo "winff.desktop" e isso será muito bom para o WinFF.  

> Let me know if you would like a name added to the Sobre -> Obrigardo box.

Você está falando sério? Você vai incluir o meu nome "marcelocripe" nos agradecimentos. Isso para mim seria um honra.
Eu sugiro adicionar os nomes das outras pessoas que estão envolvidas no WinFF que ainda foram adicionadas.

Muito obrigado!

**Comment by PeterBBBBB** [comment]
Please post your full output of
`locale -v `

What happens if you rename your .po file to 
`winff.pt_BR.UTF-8.po`  ?

**Comment by marcelocripe** [comment]
manutencao@antix1:~
$ locale -v
LANG=pt_BR.UTF-8
LANGUAGE=
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=
manutencao@antix1:~
$

**Comment by marcelocripe** [comment]
![Conversor de Multimidia WinFF em pt_BR no antiX 23 30-09-2023](https://github.com/WinFF/winff/assets/69278712/a085cf8c-a196-4710-b4ba-a6b5e9a6a7ec)

**Comment by marcelocripe** [comment]
> What happens if you rename your .po file to
> winff.pt_BR.UTF-8.po ?

With the file name "winff.pt_BR.UTF-8.po" the language "pt_BR" was successfully displayed in the WinFF Multimedia Converter graphical interface.

Could you test this solution on another GNU/Linux other than antiX Linux 23?

$ inxi -S
System:
  Host: antix1 Kernel: 6.1.42-antix.1-amd64-smp arch: x86_64 bits: 64
    Desktop: IceWM v: 3.4.2 Distro: antiX-23_x64-full Arditi del Popolo 27
    August 2023

- - - - -

> What happens if you rename your .po file to
> winff.pt_BR.UTF-8.po ?

Com o nome do arquivo "winff.pt_BR.UTF-8.po" o idioma "pt_BR" foi exibido com sucesso na interface gráfica do  Conversor de Multimídia WinFF.

Você conseguiria testar esta solução em um outro GNU/Linux diferente do antiX Linux 23?

$ inxi -S
System:
  Host: antix1 Kernel: 6.1.42-antix.1-amd64-smp arch: x86_64 bits: 64
    Desktop: IceWM v: 3.4.2 Distro: antiX-23_x64-full Arditi del Popolo 27
    August 2023

**Comment by marcelocripe** [comment]
I'm very happy to know that the problem will be fixed and that my language helped you identify the problem.

- - - - -

Eu fico muito contente em saber que o problema será corrigido e que o meu idioma te ajudou a identificar o problema.

**Comment by PeterBBBBB** [comment]
po file loading for 5 char locales should be fixed in 1.6.2

**Comment by marcelocripe** [comment]
Please don't forget to correct the file from "WinFF.pt.pdf" to "WinFF.pt_BR.pdf".

- - - - -

Por favor, não se esqueça de corrigir o arquivo de "WinFF.pt.pdf" para "WinFF.pt_BR.pdf".

**Comment by PeterBBBBB** [comment]
I'm not changing the pdfs. I mentioned this earlier. The source is still WinFF.pt_BR.odt, so its obvious what dialect it is, should someone else wish to make changes. Doing the rename you suggest results in European Portuguese users seeing the English document. (Same applies to Spanish)

**Comment by marcelocripe** [comment]
Hello [PeterBBBBB](https://github.com/PeterBBBBB).

I would like to inform you that the basic handling of WinFF was demonstrated in the video "45 - How to convert a video file to audio in antiX Linux? (WinFF Multimedia Converter)" on the YouTube channel called "antiX Linux in Portuguese" (antiX Linux em Português).

People who are not Portuguese speakers can activate the subtitles and read the automatic translation provided by YouTube of the narrator's voice script in TTSMaker. In some videos on the channel, YouTube has started to offer automatic dubbing for some languages.

Thank you very much for keeping WinFF "alive"..

Video: https://youtu.be/HuaKjjvSpDs
Mention of the video in the antiX help files (in English language of the United States of America): https://robin-antix.codeberg.page/antiX-Help-Videos/Content/en_US/index.htm

- - - - -

Olá, [PeterBBBBB](https://github.com/PeterBBBBB).

Informo que o manuseio básico do WinFF foi exibido no vídeo "45 - Como converter um arquivo de vídeo para áudio no antiX Linux? (Conversor de Multimídia WinFF)" no canal do YouTube chamado "antiX Linux em Português".

As pessoas que não são falantes do idioma português podem ativar a exibição das legendas e lerem a tradução automática que é disponibilizada pelo YouTube dos textos do roteiro da fala da voz do narrador do TTSMaker. Em alguns vídeos do canal, o YouTube passou a disponibilizar a dublagem automática para alguns idiomas.

Muito obrigado manter "vivo" o WinFF.

Vídeo: https://youtu.be/HuaKjjvSpDs
Menção do vídeo nos arquivos de ajuda do antiX (em idioma português do Brasil): https://robin-antix.codeberg.page/antiX-Help-Videos/Content/pt_BR/index.htm
