### ISSUE TITLE
Winff does not use Unicode when it passes the file names into the command prompt.

### ISSUE THREAD

**Issue by indiamcq** [WinFF/winff#255]
When I have files with accented Latin characters. The conversion fails.
The characters with accents turn into ? characters thus the conversion fails to find the file to convert.
Here are the filnames correct in the GUI.
![image](https://user-images.githubusercontent.com/1505640/206324788-f25f1ac5-0918-439c-bfc6-0176578fa4f5.png)
But looking at the FFmpeg Command Line we see the characters have changed.
![image](https://user-images.githubusercontent.com/1505640/206324974-156117b3-7283-40d1-a31c-4b0e48eca004.png)

I thought it was the command Prompt being the wrong encoding but I have eliminated that. It is changing inside of FFmpeg else.

Can this be fixed?

**Comment by PeterBBBBB** [comment]
Release 1.6.2 fixed a unicode problem, probably fixed this as well.
Please reopen if problem persists, with a cut 7 paste of the actual filename,
rather than just a screen shot. What operating system?
